campany/Controllers/addController.cs
using campany.Models;
using campany.viewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp;

namespace campany.Controllers
{
    public class addController : Controller
    {
        campanyContext context;
        
        public addController()
        {
            context = new campanyContext();
        }

        [HttpGet]
        public ActionResult Add() {
            
            return View();
        }


        [HttpPost]
        public ActionResult Add(addV add) {
            if (ModelState.IsValid)
            {
                Employee employee = new Employee()
                {
                    id = add.id,
                    name = add.name,
                    age = add.age,
                    password = add.password
                };
                context.Employees.Add(employee);
                context.SaveChanges();
                return RedirectToAction("Index", "Get");
            }
            else
            {
                return View();
            }
        }
    }
}

campany/Controllers/projController.cs
using campany.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace campany.Controllers
{
    public class projController : Controller
    {

        campanyContext context;
        public projController()
        {
            context = new campanyContext();
        }
        public IActionResult Index()
        {
            List <project> proj = context.Projects.ToList();
            return View(proj);
        }

        public IActionResult GetById(int id)
        {
            project proj = context.Projects.FirstOrDefault(e => e.Id == id);
            if (id == null)
            {
                return Content("employee not found");
            }
            return View(proj);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            project proj = context.Projects.SingleOrDefault(c => c.Id == id);
            List<project> projs = context.Projects.ToList();
            return View(proj);
        }
        [HttpPost]
        public IActionResult Edit(project proj)
        {
            project oldstudent = context.Projects.SingleOrDefault(c => c.Id == proj.Id);
            oldstudent.Name = proj.Name;
            oldstudent.Description = proj.Description;       
            context.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            try
            {
                project proj = context.Projects.SingleOrDefault(c => c.Id == id);
                context.Projects.Remove(proj);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Content("Something went wrong");
            }
        }

   

        [HttpGet]
        public IActionResult Add()
        {
            List<project> proj= context.Projects.ToList();          
            return View();
        }
        [HttpPost]
        public IActionResult Add(project proj)
        {
            context.Projects.Add(proj);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

campany/Views/proj/Add.cshtml
@model project
@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>


<form method="post">
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="Description" class="form-label"></label>
        <input asp-for="Description" class="form-control">
    </div>
   
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

campany/Views/proj/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
@model project
<h1>Edit</h1>


<form asp-controller="proj" asp-action="Edit" method="post">

    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input class="form-control" asp-for="Name">
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label"></label>
        <input class="form-control" asp-for="Description">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

campany/Views/proj/GetById.cshtml
@{
    ViewData["Title"] = "GetById";
}

<h1>GetById</h1>

<div class="card text-center">
    <div class="card-header">
    </div>
    <div class="card-body">
        <h5 class="card-title"> name => @Model.Name </h5>
        <p class="card-text">Description => @Model.Description  </p>
        <a href="/proj" class="btn btn-primary">go to offices</a>
    </div>
    <div class="card-footer text-muted">
    </div>
</div>

campany/Views/proj/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<project>
<h1>Projects</h1>

<table class="table table-info style=" width: 18rem;">
    <thead>
        <tr>
            <th> name </th>
            <th>
                crud
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var proj in Model)
        {
            <tr>
                <td>@proj.Name</td>

                <td>
                    <a href="/proj/getbyid/@proj.Id" >
                        <i class="fa-solid fa-circle-info"></i>
                    </a> //
                    <a  href="/proj/edit/@proj.Id" >
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a> //
                    <a href="/proj/delete/@proj.Id">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                </td>

            </tr>
        }
    </tbody>

</table>
<a class="btn btn-primary" href="/proj/add">Add_employee</a>